name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt hyde/scalafix hyde/test:scalafix hyde/it:scalafix && sbt hyde/scalafmtSbt hyde/scalafmt hyde/test:scalafmt hyde/it:scalafmt && sbt clean hyde/compile hyde/test:compile hyde/it:compile hyde/test && sbt coverage hyde/test hyde/it:test coverageReport && sbt coverageAggregate && sbt scalastyle test:scalastyle it:scalastyle && sbt scapegoat cpd stats
